### ISSUE TITLE
Is it possible to support Tailwind's shorthand colour opacity syntax?

### ISSUE THREAD

**Issue by tylerforesthauser** [Mokshit06/typewind#11]
I'm not sure if I just haven't figured out how this works or if this syntax is simply not yet supported, so I apologize if I missed something. But is it possible to support this syntax?

https://tailwindcss.com/blog/tailwindcss-2-2#shorthand-color-opacity-syntax

Thanks!

**Comment by Mokshit06** [comment]
This isn't possible currently but I do want to support it. Do you have any syntax recommendations in mind?

**Comment by tylerforesthauser** [comment]
Unfortunately I do not. Being limited to the JS variable character set makes it quite challenging. If I come up with anything, I'll be sure to add it here.

**Comment by Frantss** [comment]
What about one of these?

 - `tw.bg_red_500_['25']`
 - `tw.bg_red_500_['/25']`
 - `tw.bg_red_500_25`

**Comment by kavinvalli** [comment]
The first one won't be possible right now since, that syntax works with arbitrary values so it will compile to `bg-red-500-[25]`. Same with second: `bg-red-500-[/25]`. Third will just compile to `bg-red-500-25`.

First and third seem off the table for now, but we could probably work with the second to just check for / and then add it but kind of becomes way too specific, I think.

**Comment by SergeITinc** [comment]
What about?

- tw.bg_red_[500/25]

 🤔

**Comment by Mokshit06** [comment]
I think the main two options right now are:
- `tw.bg_red_500_$["25"]`
- `tw.bg_red_500_["/25"]`

The same would work for other plugins like named container queries
- `tw.$lg_$["name"](tw.text_sm)`
- `tw.$lg_["/name"](tw.text_sm)`

**Comment by SergeITinc** [comment]
I use your  tw-variants for this example
import { tw } from "tw-variants";

tw.bg_red_500_["/25"]
must comply with this options taliwind
that a choice of options would be possible 

![изображение](https://user-images.githubusercontent.com/86435624/216647019-95e7d039-d47d-4f52-ad96-b1f3fa11ee7b.png)

![изображение](https://user-images.githubusercontent.com/86435624/216649608-defeb6fc-da9a-466f-ab62-900f9376356a.png)



tw.bg_red_500$[0.24]

and this should correspond to an arbitrary value 
![изображение](https://user-images.githubusercontent.com/86435624/216648676-64772591-c116-4120-a634-a15cb70f8fb2.png)

Is that how you plan to implement it?

**Comment by SergeITinc** [comment]
I thought long and hard about it, but I'm going to suggest it anyway:
1. tw.text_red_500_25 
    I do not propose this option so that option 2 and 3 have uniformity 

2. tw.text_red_500_[25]   here _[ ] shows that this is an additional option that Tailwind has
 as is the _red and _500 option that goes along the chain

3. tw.text_red_500_$[0.24]   here _$[ ] shows that this is an arbitrary value of the optional 

----------------------------------------------------------------------------------------------------------------
Wishes and Questions

_$[0.24] Consider entering a number instead of a string. As in Tailwind itself.

It also applies to this one, for example:
typewind 
text_["40px"]  text_["#bada55"]  h_["3rem"] etc.

although in the Tailwind class itself it is possible to enter 
Tailwind 
text-[40px]  text-[#bada55]  h-[3rem]

----------------------------------------------------------------------------------------------------------------

I also don't know if this is the right behavior ?
![изображение](https://user-images.githubusercontent.com/86435624/216722833-97257788-f833-41fc-90f9-14162acab72d.png)

and when you hover your mouse over this class element, it shows this:
![изображение](https://user-images.githubusercontent.com/86435624/216723444-0cffb367-cfc5-437a-b17c-e2add4aaf1c2.png)

![изображение](https://user-images.githubusercontent.com/86435624/216723547-ad1c33fd-0a46-4caa-81c2-a7a5d1e33452.png)

Tailwind class: 
![изображение](https://user-images.githubusercontent.com/86435624/216723724-7a7362bd-17f9-471f-9ef2-c93880bc0595.png)

That's all for today.
Thank you.

**Comment by samyogdhital** [comment]
Is there any progress @SergeITinc ? I can contribute to this if you want..

**Comment by kavinvalli** [comment]
@samyogdhital We're open to contributions, but we're yet to decide on a syntax for this. Do you have any ideas about what we could do there?

**Comment by prophet1996** [comment]
could something like tw.opacity(tw.bg_sky_800,20) work?

**Comment by kavinvalli** [comment]
Hm @prophet1996, this will technically work but if we are doing this, then might as well use the actual opacity class, which will be shorter.

I think, we're moving forward with $ syntax like so:
```ts
tw.text_red_500$25 // text-red-500/25
tw.text_red_500$["0.24"] // text-red-500/[0.24]
```

**Comment by kavinvalli** [comment]
> I thought long and hard about it, but I'm going to suggest it anyway:
> 
> 1. tw.text_red_500_25
>    I do not propose this option so that option 2 and 3 have uniformity
> 2. tw.text_red_500_[25]
>    here _[ ] shows that this is an additional option that Tailwind has
>    as is the _red and _500 option that goes along the chain
> 3. tw.text_red_500_$[0.24]
>    here _$[ ] shows that this is an arbitrary value of the optional
> 
> Wishes and Questions
> 
> _$[0.24] Consider entering a number instead of a string. As in Tailwind itself.
> 
> It also applies to this one, for example: typewind text_["40px"] text_["#bada55"] h_["3rem"] etc.
> 
> although in the Tailwind class itself it is possible to enter Tailwind text-[40px] text-[#bada55] h-[3rem]
> 
> I also don't know if this is the right behavior ? ![изображение](https://user-images.githubusercontent.com/86435624/216722833-97257788-f833-41fc-90f9-14162acab72d.png)
> 
> it should probably be like this className="text_red_500 font_bold m_2 text_[40px] p_2"
> 
> Wishes you can make it like this, so it can be copied as a Tailwind class className="text-red-500 font-bold m-2 text-[40px] p-2"
> 
> and when you hover your mouse over this class element, it shows this: ![изображение](https://user-images.githubusercontent.com/86435624/216723444-0cffb367-cfc5-437a-b17c-e2add4aaf1c2.png)
> 
> ![изображение](https://user-images.githubusercontent.com/86435624/216723547-ad1c33fd-0a46-4caa-81c2-a7a5d1e33452.png)
> 
> Tailwind class: ![изображение](https://user-images.githubusercontent.com/86435624/216723724-7a7362bd-17f9-471f-9ef2-c93880bc0595.png)
> 
> That's all for today. Thank you.

@SergeITinc using it without quotes wouldn't be possible because of the limitation of using javascript/typescript syntax. It is working as an object key mapping, and if we don't add quotes, it will be invalid syntax.

**Comment by kavinvalli** [comment]
Implemented in https://github.com/Mokshit06/typewind/commit/f7c453478ff6ac35d85fd0527afa44a427ae3bd7. Check it out [here](http://localhost:3000/docs/usage/normal-usage#color-opacity)!
