### ISSUE TITLE
Using the background utility at the beginning throws a type error

### ISSUE THREAD

**Issue by guilhermefront** [Mokshit06/typewind#12]
### Link to the code that reproduces this issue
https://stackblitz.com/edit/mokshit06-typewind-d7tzbz?file=pages/index.tsx

### To reproduce
Apply any background property at the beginning (if we put it later it works), e.g: `className={tw.bg_black_500}`

### Describe the Bug
If we apply a bg_color_number (only at the beginning) it throws a type error:
```stacktrace
Type '(style: Property) => Property' is not assignable to type 'string'
```
It's like is recognizing `bg_color_number` as a variant.

### Expected Behavior
Should work as any other utility

**Comment by kavinvalli** [comment]
Hi! So `bg_black_500` isn't a class in tailwind. Ever since we added support for arbitrary variants, all undefined classes are showing up error as `Type '(style: Property) => Property' is not assignable to type 'string'`.
The error message is misleading. We might have to think of a different syntax for arbitrary variants to fix this issue @Mokshit06.

Hope this answers your doubt! Closing this issue!
