### ISSUE TITLE
Support for important modifier

### ISSUE THREAD

**Issue by guilhermefront** [Mokshit06/typewind#13]
### Describe the feature you'd like to request
Ability to apply the important modifier, e.g: `<div class="!font-bold">`
https://tailwindcss.com/docs/configuration#important-modifier

### Describe the solution you'd like
Just brute forcing some syntax alternatives there so it can quick start a discussion
`tw.font_bold_!`
`tw.font_bold['!']`
`tw.font_bold_important`

**Comment by kavinvalli** [comment]
The first one won't be possible, since typescript will parse that as a non-null assertion. The second one will be a little messy, given how typewind works currently, and will introduce a lot of unnecessary complications. The third one is very much doable, but I'm not very convinced with the syntax.

@Mokshit06 what do you think?

**Comment by Mokshit06** [comment]
I do like the third syntax, because it makes it clear which style is important and which one isn't as the property name is unique.

Will add support for this soon

**Comment by Mokshit06** [comment]
This has been added in `v0.0.10` https://github.com/Mokshit06/typewind/commit/53cf90cd446378dbeb91d21d146205af70034894. The syntax is similar to other modifiers/variants like `sm`:

```js
tw.important(tw.font_bold)
```
The docs for this will be added soon. Thanks!
