### ISSUE TITLE
Support for SWC

### ISSUE THREAD

**Issue by Bluzzi** [Mokshit06/typewind#15]
NextJS now uses SWC, but when using a Babel configuration, it disables SWC to use only Babel :

```
info - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info - Using external babel configuration from D:\...\...\Project\.babelrc
```

I'm not sure if this issue is directly related to SWC or if it belongs here?

**Comment by kavinvalli** [comment]
Hi @Bluzzi! NextJS allows you to use only one of either Babel or SWC. It's not really possible to add SWC support for Typewind right now since we're using Tailwind's officially maintained parser and would prefer to keep using that. SWC will need rust support and Tailwind seems to be working on one for rust, but it isn't done as of now so whenever it has a proper api we can look into adding SWC support.
However, we are trying to release a hybrid runtime+build version of Typewind which won't require you to use Babel and continue using SWC for your NextJS application.

**Comment by SamueleBarbiera** [comment]
> Hi @Bluzzi! NextJS allows you to use only one of either Babel or SWC. It's not really possible to add SWC support for Typewind right now since we're using Tailwind's officially maintained parser and would prefer to keep using that. SWC will need rust support and Tailwind seems to be working on one for rust, but it isn't done as of now so whenever it has a proper api we can look into adding SWC support. However, we are trying to release a hybrid runtime+build version of Typewind which won't require you to use Babel and continue using SWC for your NextJS application.

what about this integration? https://github.com/arlyon/stailwc

**Comment by Mokshit06** [comment]
Typewind v0.1.0 has support for SWC. You can use it by adding it to your `next.config.js`:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    swcPlugins: [['typewind/swc', {}]],
  },
};

module.exports = nextConfig; 
```

**Comment by kavinvalli** [comment]
Hi! We've actually added it now: https://typewind.vercel.app/docs/transpilers/swc
