### ISSUE TITLE
Type Error in Intellij

### ISSUE THREAD

**Issue by ylatmck** [Mokshit06/typewind#48]
<img width="658" alt="image" src="https://github.com/Mokshit06/typewind/assets/117431152/e263ed97-2303-4d03-9164-825c91232e26">

The css is working, only Intellij shows type error as below:

> TS2339: Property 'text_cyan_400' does not exist on type 'TypewindError"Typewind's types haven't been generated. Run `npx typewind generate` or follow the docs at https://typewind.dev/docs/installation">'.

Additional info:

- A clean setup with Vite, Babel, React, Next UI (v2)
- Done `npx typewind generate`
- Tip can show up
- `npm run build` can pass, no error.

<img width="528" alt="image" src="https://github.com/Mokshit06/typewind/assets/117431152/442403bb-fc45-4bdd-a9b9-f88a1f5807da">

Any ideas how to fix the ts error in Intellij? thanks in advance

**Comment by Mokshit06** [comment]
This is weird, this error is only shown when the type definitions haven't been generated, but since you're getting type preview and autocomplete this means they have been generated.
Is there a possibility you have 2 version of typewind maybe? I haven't personally used IntelliJ so can't comment on that.

**Comment by ylatmck** [comment]
hi @Mokshit06 thanks for your thoughts. I tried uninstall and install again, and the error is gone now, :D
