### ISSUE TITLE
Feature request: concat or conditional class names

### ISSUE THREAD

**Issue by ylatmck** [Mokshit06/typewind#51]
**Use case 1** : reusable long class names, e.g. a custom button style

If typewind has a util method to concat two (or multiple) pre-defined classnames, that will be great.

```javascript
// extract common part
const MY_BTN_CLS = tw.bg_white.rounded_full.text_black.font_bold.uppercase.border.border_black;
```

```jsx
// it works
<button className={MY_BTN_CLS}>My Button</button>

// it does not work and all styling is broken
<button className={MY_BTN_CLS.bg_cyan_500}>My Cyan Button</button>

// it works
<button className={MY_BTN_CLS.concat(" " + tw.bg_cyan_500)}>My Cyan Button</button>

// it does not work, only the last two classes are broken (due to the lack of space between them)
<button className={MY_BTN_CLS.concat(tw.bg_cyan_500)}>My Cyan Button</button>
```

**Use case 2** : conditional styling
Some variants share common base styling, and only have a few different classes, like highlight current tab
This can be done via different approaches, e.g. concat current, or extract a component to handle the style and behavior.
Also it would be of great help if typewind such a method like 
```javascript
tw.if(
    1 > 0 /* expression */, 
    tw.text_green /* yes */,  
    tw.text_red /* (optional) no */
)
```

```javascript
const baseStyles = tw.bg_white.rounded_full.text_black.font_bold.uppercase.border.border_black;
const currentStyles  = tw.bg_cyan_500.text_white;

// something like this, or `concatIf`
<button className={tw.if(isCurrent currentStyle, baseStyles)}>text</button>
```

Just my random ideas, any thoughts or comments are welcomed, :)

**Comment by Mokshit06** [comment]
Hey! I think one of your examples 
```js
<button className={MY_BTN_CLS.concat(tw.bg_cyan_500)}>My Cyan Button</button>
```
should work just fine. As for the feature request, I don't think that the complexity of adding this feature is worth it, as it would 
 require cross-file analysis to be useful, as typewind can't know if `MY_BTN_CLS` is an instance of `tw._` at compile time, which also wouldn't be possible with the swc plugin making them incompatible.
 
 `tw.if` could also be did through a ternary operator in the same amount of code. So basically rather than what this proposes:
```js
 <button className={tw.if(isCurrent, currentStyle, baseStyles)}>text</button>
 ```
 
 You can already do:
 ```js
 <button className={isCurrent ? currentStyle : baseStyles}>text</button>
 ```

Thanks for the proposal though!
