### ISSUE TITLE
Feedback for “NextJS Example”

### ISSUE THREAD

**Issue by thoushif** [Mokshit06/typewind#55]
NextJS example not working. Please check.

![image](https://github.com/Mokshit06/typewind/assets/15650121/22fc5862-b776-44f4-961d-2b7664e700ab)

**Comment by valerio-pescatori** [comment]
Same for the vite example 😕

**Comment by Mokshit06** [comment]
Hi there, this is because typewind switched over to `lightningcss` for the intellisense previews of style declaration as that improves the speed alot as compared to using prettier. Unfortunately lightningcss is not compatible with stackblitz, which is what is being used for the examples :/ They are working on supporting it though I believe. In the meanwhile I'll switch them over to codesandbox, which should fix it

**Comment by Mokshit06** [comment]
I just checked and it looks like Stackblitz has been updated to support these! The examples should be working now.
